version: '3.9'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  ideatec-api:
    build: .
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__OracleConnection=${CONNECTION_STRING}
      - ApiKey=${API_KEY}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}

volumes:
  oracle_data:
