version: '3.9'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=1234
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  ideatec-api:
    build: .
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__OracleConnection=User Id=system;Password=1234;Data Source=oracle-db:1521/XEPDB1;
      - ASPNETCORE_URLS=http://+:8080

volumes:
  oracle_data:
